### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AnalogJ** [fileago/fileago#2]
Hey,
What's the license that the source code for Fileago is published under?

**Comment by fileago** [comment]
It is closed source.

**Comment by amughrabi** [comment]
Hi there, can you please point me whether it is required to have a license for using fileago or not?

**Comment by fileago** [comment]
> Hi there, can you please point me whether it is required to have a license for using fileago or not?

Yes. Please contact support at fileago dot com for more info.
